### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kshpytsya** [ksindi/implements#1]
The `implements.py` does not get installed. Tested with:

* Python: 3.6, 3.7
* setuptools: 40.8.0, 41.0.0
* pip: 18.1, 19.0.3

This change fixes the issue.

```diff
diff --git a/setup.py b/setup.py

         include_package_data=True,
+        py_modules=['implements'],
         classifiers=textwrap.dedent("""
```

**Comment by ksindi** [comment]
Thanks @kshpytsya. Will release a fix. ~For some reason I'm not having that issue~. Misunderstood the problem.

**Comment by ksindi** [comment]
@kshpytsya released! https://pypi.org/project/implements/
