### ISSUE TITLE
TypeError when implementation has a property decorator while the interface doesn't

### ISSUE THREAD

**Issue by pshirali** [ksindi/implements#10]
The following test fails with a `TypeError`
```
def test_property_inverse():
    class FooInterface(Interface):
        def foo(self):      <--- interface defines a regular method
            pass

    with pytest.raises(NotImplementedError):
        @implements(FooInterface)
        class FooImplementationFail:
            @property
            def foo(self):  <--- implementation defines a property
                pass
```

In [verify_methods](https://github.com/ksindi/implements/blob/master/implements.py#L52)
```
cls_signature = inspect.signature(cls_method) if cls_method else None
                ^
```
With a `@property` decorator, a method is no longer callable. `inspect.signature` expects a callable. Fix: `if cls_method and callable(cls_method) else None`

**Comment by pshirali** [comment]
@ksindi fyi: I'll be opening issues to tag relevant commits with respective issue numbers. I'm assigning the issues to myself.

**Comment by ksindi** [comment]
Thanks @pshirali!
