### ISSUE TITLE
Document and prevent an implementation class inheriting an interface

### ISSUE THREAD

**Issue by pshirali** [ksindi/implements#24]
One of the common patterns to define and enforce interface relationship is where the Implementation class inherits the Interface class. This pattern can be seen in Python as well (example: `abc`)

With _implements_, an Implementation class must not inherit from an Interface class. _implements_ works by comparing methods between the interface and the implementation. When an Implementation class derives from an Interface class, missing attributes/methods in the Implementation class are not detected as they are inherited from the parent (Interface).

Proposed changes:
1. _implements_ must explicitly call this pattern out in its Documentation.
2. _implements_ can prevent this scenario by ensuring that the class hierarchies of the Implementation class, and of the Interface class have no classes in common**. 

**Skipping the root
The root class in either hierarchy may be `object` or a _metaclass_. A tradeoff (for not being too strict) could be to skip the root class entirely (and avoid handing a case of a common _metaclass_, at the root of both hierarchies)

This enhancement is a consequence of #23 

cc: @ksindi @jharwell

**Comment by ksindi** [comment]
Thanks @pshirali!
