### ISSUE TITLE
A few improvements

### ISSUE THREAD

**Issue by pshirali** [ksindi/implements#5]
Hello @ksindi ,

First, let me thank you for this amazing library. I really hope this library is used by the masses.

I created two PRs. One of them is a minor cosmetic fix. The other includes changes to the tests and a few additions as well. The PRs have failed during CI for different reasons. This gives us a chance for you to review them, and for me to make amends to resubmit the PRs.

PR #3 appears to have failed due to CI runtime. I might have to create a new commit and repush.

PR #4 has failed deepsource checks. Please feel free to review the deepsource results. I'm of the opinion that `tests.py` could additionally be excluded using [`exclude_patterns`](https://deepsource.io/docs/config/deepsource-toml.html#exclude-patterns) in the  `.deepsource.yaml` file. There will likely be future failures reported on test-code when we intentionally write code that matches a bad pattern. Further, improvements to deepsource may flag existing test-code in future PRs.

Please let me know your views.

Cheers,
Praveen

**Comment by ksindi** [comment]
Thanks @pshirali! Much appreciated. Will review and release this week.

**Comment by ksindi** [comment]
@pshirali changes released. Thanks again.

**Comment by pshirali** [comment]
Thanks @ksindi :)

PS: I noticed that you've +1'd the python minor version in multiple files. You missed `setup.py`.

**Comment by ksindi** [comment]
Oops. Thanks. Fixing.
