### ISSUE TITLE
Lib similar to implements

### ISSUE THREAD

**Issue by pshirali** [ksindi/implements#7]
Hi @ksindi . I have something similar to `implements`. I was planning to clean up the code into a library and release it under `Apache 2.0` (a licensing need that I have). While at it, I found your library too. The intent and interfaces are similar, but the implementation varies.

I'm still inclined to work & release my library under Apache 2.0, and I'm happy to contribute patches to `implements`. Since I haven't yet released it, and your library has already been in use, I wanted to know your views, and if you had any reservations in me pursuing this.

**Comment by ksindi** [comment]
Thanks @pshirali. By all means feel free to contribute to `implements`. Happy to make you a contributor to this repo as well.

**Comment by pshirali** [comment]
Thanks a lot @ksindi

**Comment by pshirali** [comment]
@ksindi are you open to relicensing `implements` from MIT to Apache 2.0, or a dual license (MIT/Apache), similar to what Rust does?

Personally, I feel having one library (`implements`) as the de facto library in the py ecosystem for interfaces is the best way to go. If you are fine with the Apache 2.0 or a dual license model, I could let go of a second lib, and just work on `implements` instead.

**Comment by ksindi** [comment]
Apache 2 works

**Comment by pshirali** [comment]
Thanks again !! :pray:
